backend/eaeo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include('main.urls', namespace='main')),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': 'media'}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': 'static'}),
]

backend/main/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('sign-in', views.SigninView, name='signin'),
    path('sign-up', views.SignupView, name='signup'),
    path('social_error_url', views.social_error_url, name='social_error_url'),

    path('new_social_auth_user', views.new_social_auth_user, name='new_social_auth_user'),
    path('influencer-sign-up', views.Influencer_signupView, name='influencer_signupview'),

    path('logout', views.logout_view, name='logout'),

    path('campaign', views.login_required(views.CampaignView.as_view()), name='campaign'),
    path('create_campaign', login_required(views.Create_campaignView.as_view()), name='create_campaign'),
    path('save_campaign', views.save_campaign, name='save_campaign'),
    path('campaign_detail/<campaign_id>', views.login_required(views.Campaign_detailView.as_view()), name='campaign'),
    path('edit_influencer_email', views.edit_influencer_email, name='edit_influencer_email'),
    path('campaign_detail/<campaign_id>/influencer_detail/<influencer_id>', views.login_required(views.Influencer_detailView.as_view()), name='inlfuencer'),

    path('accept_influencer', views.accept_influencer, name='accept_influencer'),
    path('reject_influencer', views.reject_influencer, name='reject_influencer'),

    path('brand', views.login_required(views.BrandView.as_view()), name='brand_view'),
    path('influencer', views.login_required(views.InfluencerListView.as_view()), name='influencer_view'),

    path('edit_influencer_metrics', views.edit_influencer_metrics, name='edit_influencer_metrics'),
    path('get_influencer_score', views.get_influencer_score, name='get_influencer_score'),

    path('profile', views.login_required(views.ProfileView.as_view()), name='profile'),
    path('stat', views.login_required(views.StatisticsView.as_view()), name='statistics'),
    path('notificatioin', views.login_required(views.NotificationView.as_view()), name='notification'),

    path('edit_influencer_ar', views.edit_influencer_ar, name='edit_influencer_ar'),
    path('export_pdf', views.export_pdf, name='export_pdf'),
    path('edit_influencer_additional', views.edit_influencer_additional, name='edit_influencer_additional'),
    path('edit_influencer_content', views.edit_influencer_content, name='edit_influencer_content'),
    path('edit_influencer_campaign_writeup', views.edit_influencer_campaign_writeup, name='edit_influencer_campaign_writeup'),

    path('export_png', views.export_png, name='export_png'),
    path('add_influencer', views.add_influencer, name='add_influencer'),
    path('save_influencer', views.save_influencer, name='save_influencer'),

    path('influencer_detail/<influencer_id>', views.login_required(views.InfluencerView.as_view()), name='inlfuencerview'),
]

backend/templates/base.html
{% load static %}
{% load i18n %}

<html style="height: auto; min-height: 100%;"><head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title> EAEO </title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <link rel="shortcut icon" href="/static/telmtcp/img/icon/telegrammt4.ico" type="image/x-icon">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="/static/library/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/library/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/static/library/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/library/dist/css/skins/_all-skins.css">

  <link rel="stylesheet" href="/static/library/plugins/iCheck/all.css">

  <link rel="stylesheet" href="/static/library/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">

  <link rel="stylesheet" href="/static/eaeo/main.css">

  <link rel="stylesheet" href="/static/library/bower_components/select2/dist/css/select2.min.css">

  <link rel="stylesheet" href="/static/library/dist/css/AdminLTE.min.css">

  <script src="/static/library/bower_components/jquery/dist/jquery.min.js"></script>

  <script src="/static/library/bower_components/jquery-ui/jquery-ui.min.js"></script>

  <script src="/static/eaeo/main.js"></script>
</head>
<body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">

<!-- Site wrapper -->
<div class="wrapper" style="height: auto; min-height: 100%;">

  <header class="main-header">
    <!-- Logo -->
    <a class="logo" style="background-color: #53636d;">
      <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><img src="/static/library/img/eaeo_land.png" alt="" class="img-fluid" style="max-height: 50px;"></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg hand"><img src="/static/library/img/eaeo_land.png" alt="" class="img-fluid" style="max-height: 50px;"></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" style="background-color: #53636d">
      <!-- Sidebar toggle button-->
        <!--
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        </a>
        -->
        <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a class="hand" href="{% url 'main:logout' %}">
                <span class="hidden-xs hand" id="username">Sign out</span>
            </a>
        </li></ul>
        </div>
    </nav>
  </header>

  <!-- =============================================== -->

  <!-- Left side column. contains the sidebar -->
  <aside class="main-sidebar left_sidebar_border" >
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar" style="height: auto;">
      <!-- Sidebar user panel -->
      <div class="user-panel">
      </div>
      <!-- search form -->

      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu tree" data-widget="tree">
            {% for menu in menu_data %}
              {% if menu.parent == 0 %}
                  <li class="{% if menu.id == menu_id %}active {% endif %}">
                      <a {% if menu.has_child == 0 %} href="{{ menu.url }}"{% endif %} class="{% if menu.id == menu_id %}left_sidebar_a{% endif %}">
                        <i class="{{ menu.icon }}"></i>
                        <span>{{ menu.name }}</span>
                    </a>
                  </li>
              {% endif %}
            {% endfor %}
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- =============================================== -->
    {% csrf_token %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
      {% block content %}

      {% endblock %}
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>Copyright © 2020 <a>EAEO</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->

  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->

<!-- Bootstrap 3.3.7 -->
<script src="/static/library/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- SlimScroll -->
<script src="/static/library/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/static/library/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/static/library/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/static/library/plugins/iCheck/icheck.min.js"></script>

<script src="/static/library/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/static/library/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

<script src="/static/library/bower_components/select2/dist/js/select2.full.min.js"></script>

<!--<script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBgIXZeGcXM_Hx1U_7A6q0hWvG-i2VdRqI&callback=initMap"></script>-->

<script>
  $(document).ready(function () {
    $('.sidebar-menu').tree()
  })
</script>


</body></html>